//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PHIEUNHAP
    {
        public string SoPN { get; set; }
        public string MaSP { get; set; }
        public int SLChungTu { get; set; }
        public int SLThucNhap { get; set; }
        public decimal DonGiaNhap { get; set; }
        public decimal ThanhTien { get; set; }
    
        public virtual SANPHAM SANPHAM { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
