//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKIEMKE
    {
        public string SoBBKK { get; set; }
        public string MaSP { get; set; }
        public int SLSoSach { get; set; }
        public int SLThucTe { get; set; }
        public int SLThua { get; set; }
        public int SLThieu { get; set; }
        public string PhamChat { get; set; }
    
        public virtual BBKIEMKE BBKIEMKE { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
