//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTKIEMNGHIEM
    {
        public string SoBBKN { get; set; }
        public string MaSP { get; set; }
        public int SLChungTu { get; set; }
        public int SLDungQuyCach { get; set; }
        public int SLLoi { get; set; }
        public string GhiChu { get; set; }
    
        public virtual BBKIEMNGHIEM BBKIEMNGHIEM { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
