//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        public string MaHD { get; set; }
        public string MaDH { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public decimal ThueVAT { get; set; }
        public string TrangThaiThanhToan { get; set; }
        public string MaNV { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
