//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public string MaKH { get; set; }
        public int user_id { get; set; }
        public string HoKH { get; set; }
        public string TenKH { get; set; }
        public string AnhKH { get; set; }
        public string DiaChiKH { get; set; }
        public Nullable<bool> GioiTinhKH { get; set; }
        public Nullable<System.DateTime> NgaySinhKH { get; set; }
        public string LoaiKH { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
