//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHUYENMAI()
        {
            this.DONHANGs = new HashSet<DONHANG>();
            this.SANPHAMs = new HashSet<SANPHAM>();
        }
    
        public string MaKM { get; set; }
        public string TenKM { get; set; }
        public string MoTaKM { get; set; }
        public string AnhBannerKM { get; set; }
        public Nullable<int> ThuTuHienThi { get; set; }
        public string MaVoucher { get; set; }
        public string LoaiGiam { get; set; }
        public decimal GiaTriGiam { get; set; }
        public Nullable<decimal> GiamToiDa { get; set; }
        public decimal DonToiThieu { get; set; }
        public Nullable<int> SoLuotToiDa { get; set; }
        public int SoLuotDaDung { get; set; }
        public int SoLanDungMoiKH { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public System.DateTime NgayKetThuc { get; set; }
        public string TrangThaiKM { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string MaNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONHANG> DONHANGs { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SANPHAM> SANPHAMs { get; set; }
    }
}
