//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LICHSUVANCHUYEN
    {
        public int MaLSVC { get; set; }
        public string MaVC { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public string ViTri { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual VANCHUYEN VANCHUYEN { get; set; }
    }
}
