//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        public string MaNV { get; set; }
        public int user_id { get; set; }
        public string HoNV { get; set; }
        public string TenNV { get; set; }
        public string AnhNV { get; set; }
        public string EmailNV { get; set; }
        public string SDTNV { get; set; }
        public string DiaChiNV { get; set; }
        public bool GioiTinhNV { get; set; }
        public System.DateTime NgaySinhNV { get; set; }
        public string TrangThaiLamViec { get; set; }
        public System.DateTime NgayVaoLam { get; set; }
    
        public virtual USER USER { get; set; }
    }
}
