//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        public string MaSP { get; set; }
        public string TenSP { get; set; }
        public string AnhSP { get; set; }
        public string MoTaSP { get; set; }
        public decimal GiaNhap { get; set; }
        public decimal GiaBan { get; set; }
        public bool TrangThaiSP { get; set; }
        public string ThuongHieu { get; set; }
        public Nullable<System.DateTime> NgayThemSP { get; set; }
        public string MaLoaiSP { get; set; }
        public int SoLuongTon { get; set; }
    
        public virtual DANHMUCSANPHAM DANHMUCSANPHAM { get; set; }
    }
}
