//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class THAMSO
    {
        public string MaTS { get; set; }
        public string TenTS { get; set; }
        public string Kieu_DVT { get; set; }
        public string GiaTri { get; set; }
        public string TinhTrang { get; set; }
    }
}
