//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_HOADON
    {
        public string MaHD { get; set; }
        public System.DateTime NgayLapHD { get; set; }
        public string TrangThaiThanhToan { get; set; }
        public decimal ThueVAT { get; set; }
        public string NVLapHoaDon { get; set; }
        public string MaDH { get; set; }
        public System.DateTime NgayDatHang { get; set; }
        public string KenhBan { get; set; }
        public string PhuongThucThanhToan { get; set; }
        public string TrangThaiDonHang { get; set; }
        public string NVNhanDon { get; set; }
        public string TenKH { get; set; }
        public string SoDTKhachHang { get; set; }
        public string DiaChiKH { get; set; }
        public Nullable<decimal> TongTamTinh { get; set; }
        public Nullable<decimal> TienThue { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string TenDVVC { get; set; }
        public string LoaiPhi { get; set; }
        public string TrangThaiVanChuyen { get; set; }
        public Nullable<System.DateTime> NgayGuiHang { get; set; }
        public Nullable<System.DateTime> NgayDuKien { get; set; }
        public Nullable<System.DateTime> NgayNhanHang { get; set; }
        public decimal SoTienGiam { get; set; }
    }
}
