//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SHOPGUITAR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANCHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VANCHUYEN()
        {
            this.LICHSUVANCHUYENs = new HashSet<LICHSUVANCHUYEN>();
        }
    
        public string MaVC { get; set; }
        public string MaDH { get; set; }
        public string MaDVVC { get; set; }
        public string LoaiPhi { get; set; }
        public decimal PhiVanChuyen { get; set; }
        public Nullable<System.DateTime> NgayGuiHang { get; set; }
        public Nullable<System.DateTime> NgayDuKien { get; set; }
        public Nullable<System.DateTime> NgayNhanHang { get; set; }
        public string TrangThai { get; set; }
        public string GhiChu { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual DONVIVANCHUYEN DONVIVANCHUYEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LICHSUVANCHUYEN> LICHSUVANCHUYENs { get; set; }
    }
}
